"""Generates wasm_rtcd_fallbacks.h: for every run-time dispatch entry in SVT-AV1 whose chosen implementation can't
exist in WebAssembly (NASM assembly, the CRC32-based SSE4.2 hash, or C intrinsics that call into assembly), map it to
the next implementation down in the same dispatch line.
Usage: gen_fallbacks.py <svt-av1 dir> <asm symbol list> [x86|neon]"""
import re, sys, pathlib

root = pathlib.Path(sys.argv[1])
asm = set(open(sys.argv[2]).read().split())
lib = root / 'Source/Lib'

# Functions defined in intrinsic files, with their bodies, to find which ones reach assembly.
# Bodies come from preprocessed source: several kernels build the names of the functions they call with ## pasting.
import subprocess
bodies = {}
defn = re.compile(r'^[A-Za-z_][\w \*]*?\b(\w+)\s*\([^;{]*\)\s*\{', re.M)
target = sys.argv[3] if len(sys.argv) > 3 else 'x86'
if target == 'neon':
    flags = {'NEON': '-mfpu=neon'}
    base = ['-msimd128', '-DARCH_AARCH64=1', '-DCONFIG_ARM_NEON_IS_GUARANTEED=1']
else:
    flags = {'SSE2': '-msse2', 'SSSE3': '-mssse3', 'SSE4_1': '-msse4.1', 'AVX2': '-mavx2'}
    base = ['-msimd128', '-msse4.1', '-DARCH_X86_64=1']
inc = [f'-I{root}/{d}' for d in ('Source/API', 'Source/Lib/Codec', 'Source/Lib/C_DEFAULT', 'Source/Lib/ASM_SSE2',
                                  'Source/Lib/ASM_SSSE3', 'Source/Lib/ASM_SSE4_1', 'Source/Lib/ASM_AVX2',
                                  'Source/Lib/ASM_NEON', '.')]
for f in list(lib.glob('ASM_*/*.c')):
    isa = f.parent.name[4:]
    if isa not in flags:
        continue
    src = subprocess.run(['emcc', '-E', '-P', *base, flags[isa], *inc, str(f)],
                         capture_output=True, text=True, check=True).stdout
    for m in defn.finditer(src):
        name, i, depth = m.group(1), m.end(), 1
        while depth and i < len(src):
            depth += {'{': 1, '}': -1}.get(src[i], 0)
            i += 1
        bodies[name] = src[m.end():i]
# Kernels that store pointers as 64-bit lanes; WebAssembly pointers are 32 bits (found by SVT-AV1's unit tests).
POINTER_WIDTH = {'svt_copy_mi_map_grid_avx2', 'svt_copy_mi_map_grid_neon'}
tainted = set(asm) | {n for n in bodies if 'sse4_2' in n} | POINTER_WIDTH
ident = re.compile(r'\b\w+\b')
changed = True
while changed:
    changed = False
    for name, body in bodies.items():
        if name not in tainted and any(t in tainted for t in ident.findall(body)):
            tainted.add(name)
            changed = True

# Dispatch lines: SET_xxx(ptr, c, impl1, impl2, ...). Replace tainted impls with the nearest earlier clean one.
mapping = {}
setcall = re.compile(r'\bSET_\w+\(\s*(\w+)\s*,([^;]*)\);')
for rtcd in ('Codec/common_dsp_rtcd.c', 'Codec/aom_dsp_rtcd.c'):
    for m in setcall.finditer((lib / rtcd).read_text()):
        impls = [a.strip() for a in m.group(2).split(',')]
        for k, impl in enumerate(impls):
            if impl in tainted:
                clean = next((impls[j] for j in range(k - 1, -1, -1) if impls[j] not in tainted), None)
                if clean is None:
                    sys.exit(f'no clean fallback for {impl} in {m.group(1)}')
                if mapping.get(impl, clean) != clean:
                    sys.exit(f'{impl} maps to both {mapping[impl]} and {clean}')
                mapping[impl] = clean

# Kernels written for WebAssembly (Source/Lib/ASM_WASM) that replace translated x86 ones in the x86 build.
WASM_KERNELS = {'svt_sad_loop_kernel_avx2_intrin': 'svt_sad_loop_kernel_wasm',
                'svt_ext_all_sad_calculation_8x8_16x16_avx2': 'svt_ext_all_sad_calculation_8x8_16x16_wasm'} if target == 'x86' else {}
for impl, wasm in WASM_KERNELS.items():
    mapping[impl] = wasm
    if target == 'x86':
        print(f'{impl} -> {wasm}')

with open(root / 'Source/Lib/Codec/wasm_rtcd_fallbacks.h', 'w') as out:
    out.write('/* Generated by svt-wasm/gen_fallbacks.py. WebAssembly has no NASM kernels: dispatch entries that would\n'
              ' * pick one (or an intrinsic function that calls one) fall back to the next implementation in line, and\n'
              ' * a few translated x86 kernels are replaced by ones written for WebAssembly (Source/Lib/ASM_WASM). */\n'
              '#pragma once\n')
    # Prototypes for the WebAssembly kernels, copied from their x86 counterparts in the rtcd headers.
    headers = ''.join((lib / h).read_text() for h in ('Codec/aom_dsp_rtcd.h', 'Codec/common_dsp_rtcd.h'))
    for impl, wasm in WASM_KERNELS.items():
        proto = re.search(r'\n\s*(\w[\w \*]*?\b' + impl + r'\s*\([^;]*\);)', headers)
        if not proto:
            sys.exit(f'no prototype for {impl}')
        out.write(proto.group(1).replace(impl, wasm) + '\n')
    for impl, clean in sorted(mapping.items()):
        out.write(f'#define {impl} {clean}\n')
print(f'{len(tainted & set(bodies))} intrinsic functions reach assembly; {len(mapping)} dispatch entries remapped')
